name: Deploy to AWS with Terraform

on:
  push:
    branches:
      - main  # Change this to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: <your-aws-region>  # Replace with your AWS region
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/0.15.0/terraform_0.15.0_linux_amd64.zip
          unzip terraform_0.15.0_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
      
      - name: Initialize Terraform
        run: terraform init
      
      - name: Validate Terraform Configuration
        run: terraform validate
      
      - name: Plan Terraform Changes
        run: terraform plan -out=tfplan
      
      - name: Apply Terraform Changes
        run: terraform apply -auto-approve tfplan
